@Restaurants.API_HostAddress = http://localhost:5193
@token = CfDJ8I1opdSQg8FCuZ6ipOkfd9mHzKsVxEm8iYK_YFmuzwCyMK0CgyQlw0fJEKVU3WI8piSdflIWALIQrJTkT75BAsiCzV9AfZRAJCOuryiwk0T-H_XRmwXBatD3mosT-RD6uCwYBvlSAMcha_SJIipQw93tWHss6VxLECYHYdVh70M69VowYGSYeUaG2xGcvOuECbaWsePpaDpKciUsG3y1DscUUillixel6gM9XSMryied63YF0SNU1_lU5sK332EaW-UFAH-vfQk6eKjoxeFbEFNNdaKgawDIj-sCwSNtp5G2etJhJkpO24WJPZ6vHShHX7cAlSF0nSaECC8DR4tq-YE7N5m5-_i0UQDKkjSryzNfSw5jRVgYnJuyHOZMmbsLGN6QnJJMCnUJve3PFC28KyskR0Mzhl6fRgCfzvGYMIO_17hlgfGFQJtkvlxt629ns9rKenu5PUoc7sbOMqHyiwo-vimtEgJn_UvB_riXx4w_tgbIs5fprE-2jT_3FxgcFsGXZybN1bXowt4KKux0p0N_XNDNId8dxCd8lS_SOaoLs0aaYMlyRmBAF1CgFzRy6mbyThqzZHBPxRNrgzArd1Rzv2GQNMQJ356o08Byad4B3FlhgqxLvBImAtxWnNDN2vvWYKV6IFfsZgMeVUzYLiFN2cJgTCe9li05B-uL4a-6TjC5lIMa0ZL6KbV_DRbF9_T0NEioRLvzDovewk_uSDPAS3qs67LLn0Sa-iU1KsHEaP9sUKClmlT-dywEoVLbU4-Clp8j_cFyTN141C8kT-ZNA7gDUC0V0COZBiHX-_tI

# Restaurant endpoints
### Get all restaurants
GET http://localhost:5193/api/Restaurants
#Authorization: Bearer {{token}}

### Get restaurant by Id
GET http://localhost:5193/api/Restaurants/2
Authorization: Bearer {{token}}

### Restaurant not found
GET http://localhost:5193/api/Restaurants/2

### Add new restaurant
POST  http://localhost:5193/api/Restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Test Restaurant",
  "Description": "Test Description",
  "Category": "Polish",
  "HasDelivery": true,
  "ContactEmail": "test@test.com",
  "ContactNumber": "123456789",
  "City": "Test City",
  "Street": "Test Street",
  "PostalCode": "22-222"
}

### Delete restaurant
DELETE http://localhost:5193/api/Restaurants/1

### Update restaurant
PATCH http://localhost:5193/api/Restaurants/9
Content-Type: application/json

{
  "Name": "Modified name",
  "Description": "Modified description",
  "HasDelivery": true
}

### Create dish
POST http://localhost:5193/api/restaurant/2/dishes
Content-Type: application/json

{
  "name": "Example Dish",
  "description": "Delicious dish made with fresh ingredients.",
  "price": 2,
  "kiloCalories": 2,
  "restaurantId": 1
}

### Get all dishes for specific restaurant
GET http://localhost:5193/api/restaurant/2/dishes

### Get dish by id for specific restaurant
GET http://localhost:5193/api/restaurant/2/dishes/8

### Delete all dishes for specific restaurant
DELETE http://localhost:5193/api/restaurant/2222/dishes

### Delete dish by id for specific restaurant
DELETE http://localhost:5193/api/restaurant/2/dishes/6

### User Register
POST http://localhost:5193/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Asdfasdf1!"
}

### User Login
POST http://localhost:5193/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Asdfasdf1!"
}

### Update user details
PATCH http://localhost:5193/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "dateOfBirth": "01-01-2022",
  "Nationality": "Polish"
}




