@Restaurants.API_HostAddress = http://localhost:5193
@token = CfDJ8I1opdSQg8FCuZ6ipOkfd9mN0WjhMYBs1zoTk3rAiPsgT_ElKjpxL9h-O41dsl70iB6iD4LyKfXk0qSzdGN1ebr1KEOeKgjLjpy40DgTwhjfNZAz6m9JAD2TdlZX2M5pWu7VZWIA5WNocUHsI_GdlUkCV6NtA2ijmpwqywwpDDrpJ-FPfoBbVHISsLj0M63K8lyKdoAr4E33sngqxoc7L2l4h8ds60FqDTdmFx4l4OYG-f4yQCQVV54nM7z_Hf8rKRZPmxOBUqxrZkN8XVD2OfrWcP-UNdVOvD00pqBl4Ip_D914QexO1EbimhxogccYk9i8elOqrVAhBdxXVFi3P1yxRW-IFV9Y1E0paEOiAu1FpqIXgY3kMJfMN_b2F0gni13BARf7n-h738f4eMBK3cTbleeoAI1R-FlfWNT95W-ZHeBGUxs_87E6Y1blJZbmMt5YY5qmJLV1_8iJGcHotwUdXe_cIGuF8kNSLw5x1aG_Wsbvz7TA5rInmB74GLIXN6-GFD6qMWEGuba3PB6segNhwcWbZFNvj82XyAX09u3Ul2N3Cpu443lAiJ1DzFKpqNlV9GaykiRW5Px2gY-ZhwcgWYQQeGZsbR4vz8t1MkSyFwa-geKIZ3RN3xeBoYd9F8KNybosWP6VyZbDvHaS28atEZdLtK6I6U8D9JAGCOFwRO5ZYNDerlDjlf6y-ZaClO_KEdyn0B3jB4_UUffepqQkn9rVhnTaSVdSpA1M6dQ96XalTaAp7PXfaZz_Mf0GzJKvAvhNV1_Dy2H3oWHiHsMXwrlyUN8jL7rbC01iO4hkeVwZM8Wsyy9-CBW-BJJB3iVo1oRHxtVX1nhKozYe5X8

# Restaurant endpoints
### Get all restaurants
GET http://localhost:5193/api/Restaurants
#Authorization: Bearer {{token}}

### Get restaurant by Id
GET http://localhost:5193/api/Restaurants/2
Authorization: Bearer {{token}}

### Restaurant not found
GET http://localhost:5193/api/Restaurants/2

### Add new restaurant
POST  http://localhost:5193/api/Restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Test Restaurant",
  "Description": "Test Description",
  "Category": "Polish",
  "HasDelivery": true,
  "ContactEmail": "test@test.com",
  "ContactNumber": "123456789",
  "City": "Test City",
  "Street": "Test Street",
  "PostalCode": "22-222"
}

### Delete restaurant
DELETE http://localhost:5193/api/Restaurants/1

### Update restaurant
PATCH http://localhost:5193/api/Restaurants/9
Content-Type: application/json

{
  "Name": "Modified name",
  "Description": "Modified description",
  "HasDelivery": true
}

### Create dish
POST http://localhost:5193/api/restaurant/2/dishes
Content-Type: application/json

{
  "name": "Example Dish",
  "description": "Delicious dish made with fresh ingredients.",
  "price": 2,
  "kiloCalories": 2,
  "restaurantId": 1
}

### Get all dishes for specific restaurant
GET http://localhost:5193/api/restaurant/2/dishes

### Get dish by id for specific restaurant
GET http://localhost:5193/api/restaurant/2/dishes/8

### Delete all dishes for specific restaurant
DELETE http://localhost:5193/api/restaurant/2222/dishes

### Delete dish by id for specific restaurant
DELETE http://localhost:5193/api/restaurant/2/dishes/6

### User Register
POST http://localhost:5193/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Asdfasdf1!"
}

### User Login
POST http://localhost:5193/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Asdfasdf1!"
}

### Update user details
PATCH http://localhost:5193/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "dateOfBirth": "01-01-2022",
  "Nationality": "Polish"
}




