@Restaurants.API_HostAddress = http://localhost:5193
@token = CfDJ8I1opdSQg8FCuZ6ipOkfd9n6y5v6Bv_INjgrYKCqQ9qPtOGfSkG_0Yatn089rETUeGgkruuVMwbm9Wn1whnp9GaXeqrZ4aYGFEBJCdymQ1tG__axvXQJXvPXlwuwcFiQ1K7ZXWAe2PMexJZB9P1f-ge0nIbRCi58YCKBfzpt0QNGXpJINefyIJuas-ldNU0xzaTyzUcGAUnbet6hbxwAt9EjiZ19-5WZ0mHIsCgRBcdOLxU-cR2_6bGaBlQD_2vHzNjCH1r--CGZmepcTCh3TAPs65Drfb6o9-AE-s9xh82ydXKyVyA1vJR2mQP-j9OZkT9MGR9sHPUnkpFB_v5gL8gz1W29RwxfT5NbCamn4_kBIhTZx82ipI_yiYgv_sa5-mt5Jg_j4Jb0-WSC0We4HedLN_KolPArr-ZKGTQ0nqzmEhSj5OLRv_FCtx9wL7-u0JMgmfDbU6EtBgo3VfK3krksec-lKatKdvx8HXfILetv54EbfwY3DB3ywEPMH5K831dFx-NogTT5RGTAW54zLUPxAHqmIAQ6q_n06sh5FlxYeYOIR7cq-nwaHeOjN39monaaT2UOg7hBSkgatVJWyVu7HI8k32YimFLjX3qaLSiFPqUrbhyqgq4ia3WytMW-SdSQdxwCfbCeQkqQ3U-2CaPWOGX-RzxglCbmT3Ee8EYwjawJgXfJln_XnzB5nNEDyeXrbXwZZKKkv9iNtIaI9gxZ0geYCqg8xWtcqdE8y88tAlD-T8Rqp7l3t2eGU-y2sXjSGsci5RmezLueOLrbNqHkzFQa8PR2nBOvc68q3ozaauVC4WN_0D-DNGO5N1NlZKuFx5Kg38MNTXWFeLYxS0T6BIzZmoIsflnRay61PuCJ

# Restaurant endpoints
### Get all restaurants
GET http://localhost:5193/api/Restaurants
#Authorization: Bearer {{token}}

### Get restaurant by Id
GET http://localhost:5193/api/Restaurants/2
Authorization: Bearer {{token}}

### Restaurant not found
GET http://localhost:5193/api/Restaurants/2

### Add new restaurant
POST  http://localhost:5193/api/Restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Test Restaurant",
  "Description": "Test Description",
  "Category": "Polish",
  "HasDelivery": true,
  "ContactEmail": "test@test.com",
  "ContactNumber": "123456789",
  "City": "Test City",
  "Street": "Test Street",
  "PostalCode": "22-222"
}

### Delete restaurant
DELETE http://localhost:5193/api/Restaurants/13
Authorization: Bearer {{token}}

### Update restaurant
PATCH http://localhost:5193/api/Restaurants/7
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Modified name",
  "Description": "Modified description",
  "HasDelivery": true
}

### Create dish
POST http://localhost:5193/api/restaurant/2/dishes
Content-Type: application/json

{
  "name": "Example Dish",
  "description": "Delicious dish made with fresh ingredients.",
  "price": 2,
  "kiloCalories": 2,
  "restaurantId": 1
}

### Get all dishes for specific restaurant
GET http://localhost:5193/api/restaurant/2/dishes
Authorization: Bearer {{token}}

### Get dish by id for specific restaurant
GET http://localhost:5193/api/restaurant/2/dishes/8

### Delete all dishes for specific restaurant
DELETE http://localhost:5193/api/restaurant/2222/dishes

### Delete dish by id for specific restaurant
DELETE http://localhost:5193/api/restaurant/2/dishes/6

### User Register
POST http://localhost:5193/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Asdfasdf1!"
}

### User Login
POST http://localhost:5193/api/identity/login
Content-Type: application/json

{
  "email": "a@a.com",
  "password": "Asdfasdf1!"
}

### Update user details
PATCH http://localhost:5193/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "DateOfBirth": "1990-01-01",
  "Nationality": "Polish"
}

### Assign role (admin)
POST http://localhost:5193/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
"UserEmail": "a@a.com",
"RoleName": "Owner"
}


